### ISSUE TITLE
File not found error for ~/.ssh/config when launching Jupyterlab

### ISSUE THREAD

**Issue by siliang-j-1225** [xinsnake/datascience-e2e#2]
There is a file not found error came out after running 
`dj $SSH_PROFILE -k -o $DATABRICKS_ORG_ID
`

```
Valid version of conda detected: 4.8.3

* Getting host and token from .databrickscfg

* Select remote cluster

? Which cluster to connect to?  0: 'cluster-1' (id: 0720-061000-bowel822, state: TERMINATED, scale: 2-8)                                 
   => Starting cluster 0720-061000-bowel822
   => Waiting for cluster 0720-061000-bowel822 being started (this can take up to 5 min)
   ........................................
   => OK

   => Waiting for libraries on cluster 0720-061000-bowel822 being installed (this can take some time)
   
   => OK

   => Selected cluster: cluster-1 (13.75.170.26)

* Configuring ssh config for remote cluster
   => ~/.ssh/config will be changed
   => A backup of the current ~/.ssh/config has been created
   => at ~/.databrickslabs_jupyterlab/ssh_config_backup/config.2020-07-21_01-07-28
Traceback (most recent call last):
  File "/opt/conda/envs/db-jlab/bin/dj", line 293, in <module>
    prepare_ssh_config(cluster_id, profile, public_ip)
  File "/opt/conda/envs/db-jlab/lib/python3.7/site-packages/databrickslabs_jupyterlab/local.py", line 227, in prepare_ssh_config
    shutil.copy(config, os.path.expanduser(backup))
  File "/opt/conda/envs/db-jlab/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/envs/db-jlab/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.ssh/config'

```

**Comment by xinsnake** [comment]
Fixed with https://github.com/xinsnake/datascience-e2e/commit/ab58e6f4a603ca0d90b25a36f7a61c37099affa2
